### ISSUE TITLE
integrate parsing of MMTF structures

### ISSUE THREAD

**Issue by enauz** [cleberecht/singa#60]
- MMTF is a highly optimized and compressed format of macromolecular structures
- this could substantially speed up structure parsing
- http://mmtf.rcsb.org/index.html

**Comment by cleberecht** [comment]
The implementation is basically ready with commit 61e4fcf.
We need to merge the existing graphs oriented pattern with the mmtf structure. Further, we need to check which methods are really required and which are able to be implemented. Currently no removal of elements from any structural level is provided in the interface, although it should be possible to remove the referencing identifiers to remove access. Afterwards the existing chemical package needs to be updated to work with the new interfaces instead of the actual implementations.

**Comment by cleberecht** [comment]
first (quite) stable implementation since 59b343d
